# Generated by Django 3.0.1 on 2020-01-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='Publisher_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='p_library.Publisher'),
            preserve_default=False,
        ),
    ]
